### ISSUE TITLE
add hover-effect on the links in the footer

### ISSUE THREAD

**Issue by shubhangi013** [Catrobat/Catroweb#2022]
There should be a hover effect on the links provided in the footer. It could be a color change similar to the sidebar links.

**Comment by himanshu007-creator** [comment]
Hey, i would like to work on this issue. Please guide me further how to get started😁

**Comment by wslany** [comment]
These pages are intended to be used on phones only. So...

**Comment by dmetzner** [comment]
In addition, there is a hover effect anyway.
![image](https://user-images.githubusercontent.com/40868718/135667340-25091caf-89b3-435d-a277-e11fa0dfabc8.png)
